server:
  port: 9000

#mysql setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-n9ji5-kr.vpc-pub-cdb.ntruss.com:3306/studydb?serverTimezone=Asia/Seoul
    username: study
    password: bitcamp!@#123

  #jpa setting
  #ddl-auto: create(?? ???? ?? ? ?? ?? : ?? ???? ??), update(??? ??? ??)
  jpa:
    hibernate:
      ddl-auto: update
    #ddl ??? ??? ??? ??? ??? ??? ????
    generate-ddl: true
    # api ??? ???? sql ?? ??? ??? ????
    show-sql: true
    # ??? ??? ??? ??
    database: mysql
    #MySQL ?? ??
    database-platform: org.hibernate.dialect.MySQLDialect
    #database-platform: org.hibernate.dialect.MySQL57Dialect

  #?? ??? .?? /? ??? ? ???? -> ??? ?
  #mvc:
  #  view:
  #    prefix: /templates
  #    suffix: .html
